library(lmerTest)
gtadsp<-read.csv(file="gtadsp.csv")
m=lmer(PHC_MEM~PTGENDER_name+PTEDUCAT_name+apoe4+age*(g1+g2+g3)+(1|RID),data=gtadsp)
capture.output(summary(m), file="adsp.lm.output.txt")
m=lmer(PHC_VSP~PTGENDER_name+PTEDUCAT_name+apoe4+age*(g1+g2+g3)+(1|RID),data=gtadsp)
capture.output(summary(m), file="adsp.lm.output.txt",append=T)
m=lmer(PHC_LAN~PTGENDER_name+PTEDUCAT_name+apoe4+age*(g1+g2+g3)+(1|RID),data=gtadsp)
capture.output(summary(m), file="adsp.lm.output.txt",append=T)
m=lmer(PHC_EXF~PTGENDER_name+PTEDUCAT_name+apoe4+age*(g1+g2+g3)+(1|RID),data=gtadsp)
capture.output(summary(m), file="adsp.lm.output.txt",append=T)
