library(lmerTest)
gtcdr<-read.csv(file="gtcdr.csv")
m=lmer(CDGLOBAL~PTGENDER_name+PTEDUCAT_name+age*(g1+g2+g3)+apoe4+(1|RID),data=gtcdr)
capture.output(summary(m), file="cdr.lm.output.txt")
m=lmer(CDMEMORY~PTGENDER_name+PTEDUCAT_name+age*(g1+g2+g3)+apoe4+(1|RID),data=gtcdr)
capture.output(summary(m), file="cdr.lm.output.txt",append=T)
m=lmer(CDORIENT~PTGENDER_name+PTEDUCAT_name+age*(g1+g2+g3)+apoe4+(1|RID),data=gtcdr)
capture.output(summary(m), file="cdr.lm.output.txt",append=T)
m=lmer(CDJUDGE~PTGENDER_name+PTEDUCAT_name+age*(g1+g2+g3)+apoe4+(1|RID),data=gtcdr)
capture.output(summary(m), file="cdr.lm.output.txt",append=T)
m=lmer(CDHOME~PTGENDER_name+PTEDUCAT_name+age*(g1+g2+g3)+apoe4+(1|RID),data=gtcdr)
capture.output(summary(m), file="cdr.lm.output.txt",append=T)
m=lmer(CDCARE~PTGENDER_name+PTEDUCAT_name+age*(g1+g2+g3)+apoe4+(1|RID),data=gtcdr)
capture.output(summary(m), file="cdr.lm.output.txt",append=T)
